#!/usr/bin/env sh

# the scripting-addition must be loaded manually if
# you are running yabai on macOS Big Sur. Uncomment
# the following line to have the injection performed
# when the config is executed during startup.
#
# for this to work you must configure sudo such that
# it will be able to run the command without password
#
# see this wiki page for information:
#  - https://github.com/koekeishiya/yabai/wiki/Installing-yabai-(latest-release)
#
# sudo yabai --load-sa
# yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

# global settings
yabai -m config mouse_follows_focus          off
yabai -m config focus_follows_mouse          off
yabai -m config window_placement             second_child
yabai -m config window_topmost               off
yabai -m config window_shadow                float
yabai -m config window_opacity               on
yabai -m config active_window_opacity        1.0
yabai -m config normal_window_opacity        0.90
yabai -m config window_border                off
# yabai -m config window_border_width          1
# yabai -m config active_window_border_color   0xff775759
# yabai -m config normal_window_border_color   0xff555555
# yabai -m config insert_feedback_color        0xaad75f5f
yabai -m config split_ratio                  0.50
yabai -m config auto_balance                 off
yabai -m config mouse_modifier               fn
yabai -m config mouse_action1                resize
yabai -m config mouse_action2                move
yabai -m config mouse_drop_action            swap
yabai -m config mouse_follows_focus          off

# general space settings
yabai -m config layout                       bsp
yabai -m config top_padding                  5
yabai -m config bottom_padding               5
yabai -m config left_padding                 5
yabai -m config right_padding                5
yabai -m config window_gap                   6

# focus next window on closing current window
# yabai -m signal --add event=window_destroyed \
  # action="yabai -m query --windows --window &> /dev/null \
  # || yabai -m window --focus recent \
  # || yabai -m window --focus first"
# yabai -m signal --add event=application_terminated \
  # action="yabai -m query --windows --window &> /dev/null \
  # || yabai -m window --focus recent \
  # || yabai -m window --focus first"

# app settings
yabai -m rule --add app="^(System Preferences|CleanShot X|Raycast)$" manage=off
yabai -m signal --add event=window_created  app='^(CleanShot X)$' \
  action='yabai -m window "${YABAI_WINDOW_ID}" --opacity 1.0'
yabai -m signal --add event=window_created \
  action='\
  yabai -m query --windows --window $YABAI_WINDOW_ID \
  | jq -er "select(.resizable == 0 and .floating == 0) .id" \
  && yabai -m window $YABAI_WINDOW_ID --toggle float \
  && yabai -m window --move abs:500:300'

